#!/bin/sh
# /etc/init.d/psyrcd
#
# Sys-V init script for psyrcd, the Psybernetics IRC server.
# Luke Brooks (luke@psybernetics.org.uk)
#
# You generally want to fill out the username below
# and probably place this psyrcd directory in /srv.
# Make sure your log directory is owned by your $USER.

BASEDIR=/srv/psyrcd

USER=
SCRIPTS=$BASEDIR/scripts/
PIDFILE=$BASEDIR/pid
LOGFILE=/var/log/psyrcd/ircd.log

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting psyrcd"
    echo q|psyrcd --run-as=$USER --logfile=$LOGFILE --pidfile=$PIDFILE --scripts-dir=$SCRIPTS --preload
    ;;
  stop)
    echo "Stopping psyrcd"
    psyrcd --stop --pidfile=$PIDFILE
    ;;
  *)
    echo "Usage: /etc/init.d/psyrcd {start|stop}"
    exit 1
    ;;
esac

exit 0

